// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnndfixhkbmbsrecqamr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubmRmaXhoa2JtYnNyZWNxYW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDUxNjcsImV4cCI6MjA2NDcyMTE2N30.7kWyCZIKNV70K-oCPLBdf31vbsI9iZ_d6coiCPjBlmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);